### ISSUE TITLE
'crest_sampling' Failing During Complex Generation

### ISSUE THREAD

**Issue by ankur56** [lanl/Architector#15]
Hello,

I am trying to generate metal complexes with `"crest_sampling": True`; however, I always get the following error.

```
abnormal termination of crest
Traceback (most recent call last):
  File "/global/scratch/users/ankur/test_architector/test_arch.py", line 46, in <module>
    out = build_complex(inputDict) # Might take forever
  File "/global/scratch/users/ankur/conda_envs/arch/lib/python3.9/site-packages/architector/complex_construction.py", line 730, in build_complex
    samples,energies = io_crest.crest_conformers(vals[i]['mol2string'],solvent=tmp_inputDict['parameters']['xtb_solvent'])
  File "/global/scratch/users/ankur/conda_envs/arch/lib/python3.9/site-packages/architector/io_crest.py", line 171, in crest_conformers
    sub.run(execStr,shell=True,check=True)
  File "/global/scratch/users/ankur/conda_envs/arch/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/global/scratch/users/ankur/crest/crest structure.xyz --gfn2//gfnff --chrg -1 --alpb water --notopo --quick > output.crest' returned non-zero exit status 128.
```
Also, I couldn't find the `structure.xyz` file in the working directory.

**Comment by mgt16-LANL** [comment]
Hi @ankur56! Thanks for reaching out and for trying out Architector - I'm sorry you are having trouble getting the crest integration working! Unfortunately this particular issue might be either on the crest side or on the Architector side. I was just able to test the interface and see that it is at least working on a more simple system - for example:
```python
from architector import (build_complex, 
                         view_structures)
out = build_complex({'core':{'metal':'Fe','coreCN':6},
                     'ligands':['water'],
                     'parameters':{'assemble_method':'UFF','full_method':'GFN2-xTB',
                                   'crest_sampling':True,
                                  'xtb_solvent':'water'}
                    })
view_structures(out)
```
Produces the following structures:
<img width="586" alt="image" src="https://github.com/lanl/Architector/assets/119455260/16f99b69-f4aa-40ca-b95d-b58ca30512e3">
Along with the crest structures (as ASE atoms objects and energies in the output dictionaries):
<img width="991" alt="image" src="https://github.com/lanl/Architector/assets/119455260/8063fed7-acb4-4442-8316-78302fb0eeba">

From what you sent - I'd venture that there's a chance crest with the given input options is failing to generate structures for you. 

As a first pass I'd suggest starting by seeing if you can run the example I show above for yourself. In case this fails there may be an installation issue we need to take care of - otherwise to start to debug Architector/Crest I'd suggest trying to run crest with different options on architector-produced structures. For example - from a generation that doesn't attempt to perform crest sampling you can write out one of the successfully-generated structures as structure.xyz like this:
<img width="991" alt="image" src="https://github.com/lanl/Architector/assets/119455260/8a78fc67-0079-42d4-b5aa-033a2006307d">

And then try crest from the command line just as you saw from the error you were receiving:
`/global/scratch/users/ankur/crest/crest structure.xyz --gfn2//gfnff --chrg -1 --alpb water --notopo --quick > output.crest` to potentially debug/see what's going on.

The Crest integration in Architector is admittedly less stress-tested on different systems than many of the other features so any additional information you could give on your test systems or systems that are causing this failure would be very useful!

**Comment by ankur56** [comment]
@mgt16-LANL Thank you for your comprehensive reply. My apologies for the delayed response from my end, as we have been testing various CREST options to optimize Architector's performance for our specific use case, involving lanthanide complexes. We discovered that the error originates from CREST rather than Architector itself. The computations execute without any issues when we include the `--nocross` and `--noreftopo` flags in the CREST command. We also included `--T` flag to make it run on multiple threads.

**Comment by mgt16-LANL** [comment]
Hi @ankur56 - Thanks so much for the feedback and info. I'll work on exposing more of the command line crest options to users in case they want to play with this at a lower level within Architector like you had done. I should have a PR up sometime within the next few days. I might make your suggestions default in the crest command line options in Architector if that's okay! I hadn't played around with`--nocross` yet at all.
