### ISSUE TITLE
meaning of "n_conformers" and “n_symmetries”

### ISSUE THREAD

**Issue by S1chemf** [lanl/Architector#18]
Hello,

I am confused as to the meaning of "n_conformers" and “n_symmetries”. It says in README.md that NSymmetries should be >= n_conformers. However, in Debugging_Guide.ipynb, it says that "n_symmetries" should always be less than or equal to "n_conformers". 

Also, when my input contains:
'n_conformers’:1,
"n_symmetries": 10,
"skip_duplicate_tests": True ,

6 complexes are built. 

And when my input contains:
'n_conformers’:1,
"n_symmetries": 10,
"skip_duplicate_tests": False ,

5 complexes are built.

However, when my input contains:
'n_conformers’:3,
"n_symmetries": 3,
"skip_duplicate_tests": False ,

11 complexes are built.

How are the final number of built conformers decided based on these parameters?

**Comment by mgt16-LANL** [comment]
Good Question S1chemf! First, thanks for using Architector and for reaching out with your question and I apologize for the delayed response! You found a definite clash between the debugging document and the README.md and Debugging_Guide.ipynb. In this case the README.md is correct and I am updating the debugging guide based on your question. I created a quick example to illustrate n_symmetries vs. n_conformers you should be able to play around with:

1. n_symmetries:1 and n_conformers:1:
```python
from architector import (build_complex, 
                         view_structures)
out = build_complex({'core':{'metal':'Fe','coreCN':6},
                     'ligands':['water']*3+['chloride','bromide','iodide'],
                     'parameters':{'n_symmetries':1, 'n_conformers':1, 'skip_duplicate_tests':True, 'relax':False}
                    })
view_structures(out)
```
This should produce 4 structures - one for each metal center symmetry: octahedral, pentagonal_pyramidal, trigonal_prismatic, and hexagonal planar. The 'skip_duplicate_tests' and 'relax':False keywords force Architector to return all structures regardless if they converge to sane geometries at the GFN2-xTB level of theory or create nearly identical structures.

2. n_symmetries:2 and n_conformers:1:
```python
out = build_complex({'core':{'metal':'Fe','coreCN':6},
                     'ligands':['water']*3+['chloride','bromide','iodide'],
                     'parameters':{'n_symmetries':2, 'n_conformers':1, 'skip_duplicate_tests':True, 'relax':False}
                    })
view_structures(out)
```
This should produce 4 structures again - one for each metal center symmetry: octahedral, pentagonal_pyramidal, trigonal_prismatic, and hexagonal planar. But will potential produce some structures with different ligand symmetries than before (it did for me) since more ligand symmetries are tested. 

3. n_symmetries:2 and n_conformers:2:
```python
out = build_complex({'core':{'metal':'Fe','coreCN':6},
                     'ligands':['water']*3+['chloride','bromide','iodide'],
                     'parameters':{'n_symmetries':2, 'n_conformers':2, 'skip_duplicate_tests':True, 'relax':False}
                    })
view_structures(out)
```

This should produce 8 structures now - two for each metal center symmetry: octahedral, pentagonal_pyramidal, trigonal_prismatic, and hexagonal planar.

**Note** that if you remove the 'skip_duplicate_tests' and 'relax' keywords, Architector will give you fewer structures than this maximum of 8 since Architector will remove some structures that 1. will be unstable at the GFN2-xTB level of theory(particularly the planar geometry) or 2. After GFN2-xTB relaxation converge to nearly identical geometries.

I'm also attaching a screenshot of this code executed for reference:
![image](https://github.com/lanl/Architector/assets/119455260/0aae5e4e-ce35-4c86-8d49-723eeeb862d5)
